services:
  - type: web
    name: ukuu-hr-csharp
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DOTNET_SYSTEM_GLOBALIZATION_INVARIANT
        value: "false"
